### PR TITLE
bug report: Add validation in bug report submission

### LINKED ISSUE #96: Empty bug reports should be validated.
Empty and blank spaces are also being submitted in the bug reports section.

### PR DESCRIPTION
**Pull request by palindrome69**
Fixes #96

### CODE REVIEW

File: routes/dashboard/index.js [hunk 1]
```diff
@@ -239,32 +241,57 @@ router.get("/bug", function(req, res, next) {
...
-    student: req.user.email
-  };
-  bugsModel.create(dataStore, function(err, response) {
-    if (err) {
+router.post(
+  "/bug",
+  [
+    check("feedbacklist")
+      .exists()
+      .not()
```
Comment (Kailash0311) [inline routes/dashboard/index.js]: Use `.withMessage` method to provide custom errors.

File: routes/dashboard/index.js [hunk 2]
```diff
@@ -239,32 +241,57 @@ router.get("/bug", function(req, res, next) {
...
+      .equals(". . ."), // default value in the category selector
```
Comment (Kailash0311) [inline routes/dashboard/index.js]: Use .withMessage method to provide custom errors.

File: routes/dashboard/index.js [hunk 3]
```diff
@@ -239,32 +241,57 @@ router.get("/bug", function(req, res, next) {
...
+    check("feedback")
```
Comment (Kailash0311) [inline routes/dashboard/index.js]: Use `.withMessage` while checking this field also.

**Comment by Kailash0311** [comment]
refer already written code in this codebase or for the official documentation refer [valiadation-chain-api](https://express-validator.github.io/docs/validation-chain-api.html)

**Comment by Kailash0311** [comment]
Merged, thanks @palindrome69
